kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
  namespace: ci
subsets:
  - addresses:
      - ip: 192.168.22.21
    ports:
      - port: 20
  - addresses:
      - ip: 192.168.22.22
    ports:
      - port: 20

---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
  namespace: ci
spec:
  ports:
    - port: 20

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-cluster
  namespace: ci
  labels:
    pv: glusterfs-cluster
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-5g
  namespace: ci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: glusterfs-cluster
