#--------------------------- log inputs ------------------------------
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /log/path/app1.log
  multiline.pattern: '^feign|^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  tags: ["goods"]

- type: log
  enabled: true
  paths:
    - /log/path/app2.log
  multiline.pattern: '^feign|^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  tags: ["order"]

- type: log
  enabled: true
  paths:
    - /log/path/app3.log
  multiline.pattern: '^feign|^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  tags: ["shopping"]

- type: log
  enabled: true
  paths:
    - /log/path/app4.log
  multiline.pattern: '^feign|^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  tags: ["user"]
  
#--------------------------- redis output ------------------------------
output.redis:
  hosts: ["10.88.0.x:6379"]
  key: "app-log

xpack.monitoring.enabled: false
##--Kevin
