apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
  namespace: ci
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
     metadata:
       labels:
         app: tomcat
     spec:
       containers:
       - image: docker.io/tomcat
         name: tomcat
         #resources:
         #  limits:
         #    cpu: "1"
         #    memory: 200Mi
         ports:
         - containerPort: 8080
         volumeMounts:
         - name: httpd-storage
           mountPath: /usr/local/tomcat/webapps/ROOT
       volumes:
       - name: httpd-storage
         nfs:
           server: 192.168.22.8
           path: /data/web
