#--------------------------- log inputs ------------------------------
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/aa.log
#--------------------------- consolidate examples ----------------------
#  multiline.pattern: '^\<|^com\.freemud|^feign\.com|^[[:space:]]{2}|^Caused by:'
#  multiline.negate: false
#  
  multiline.pattern: '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}[[:space:]][0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}'
  multiline.negate: true
  multiline.match: after
  tags: ["api-gateway"]


#--------------------------- keep fields from events -------------------
#processors:
#  - drop_fields:
#      fields: ["_score","_type","input.type","beat.hostname","beat.name","beat.version"]
#
processors:
  - include_fields:
      fields: ["host.name","source","tags","message"]

#------- drop event example ---------
  - drop_event:
      when:
          regexp:
              message: "Resolving eureka"


#--------------------------- redis output ------------------------------
output.redis:
  hosts: ["10.88.6.195:6379"]
  key: "api-gateway"

xpack.monitoring.enabled: false

##--Kevin

