#--------------------------- log inputs ------------------------------
## 采集日志，如有多个把 -type: log下面的部分复制一份
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/aa.log
#--------------------------- consolidate examples ----------------------
#  multiline.pattern: '^\<|^com\.freemud|^feign\.com|^[[:space:]]{2}|^Caused by:'
#  multiline.negate: false
## 多行合并，以[日期 时间] 为全并条件
  multiline.pattern: '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}[[:space:]][0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}'
  multiline.negate: true
  multiline.match: after
  tags: ["aaa"]


#--------------------------- keep fields from events -------------------
#processors:
#  - drop_fields:
#      fields: ["_score","_type","input.type","beat.hostname","beat.name","beat.version"]
# 在日志采集分片过程中，只保留以下字段，备：不管有没有保留temptime和type，他们都会存在不能移除
processors:
  - include_fields:
      fields: ["host.name","source","tags","message"]

#------- drop event example ---------
## 过滤message内容为 "Resolving eureka" ,遇到此类则删除消息
  - drop_event:
      when:
          regexp:
              message: "Resolving eureka"


#--------------------------- redis output ------------------------------
output.redis:
  hosts: ["10.1.1.100:6379"]
  key: "aaa"

xpack.monitoring.enabled: false

##--Kevin

