apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
        containers:
        - image: img.reg.3g:15000/mysql:5.7.13
          name: mysql
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
 
 
 
 apiVersion: v1
 kind: Service
 metadata:
   name: mysql
 spec:
   ports:
   - name: mysql-svc
     port: 3306
     targetPort: 3306
     nodePort: 31101
   selector:
     app: mysql
   type: NodePort
   
   
   
   
