##创建namespaces ci
apiVersion: v1
kind: Namespace
metadata:
   name: ci
   labels:
     name: ci
     
##创建Glusterfs的PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jenkins
  namespace: ci
  labels:
    pv: nfs-jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/jenkins
    server: 192.168.22.8
#  glusterfs:
#    endpoints: "glusterfs-cluster"
#   path: "k8s-volume"
#    readOnly: false
   
##创建PVC 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv
  namespace: ci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: nfs-jenkins

##创建ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: ci
  
##创建RBAC权限
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: ci

##部署Jenkins应用
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      serviceAccount: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: home
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: jenkins-pv

##给Jenkins端口暴露
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: ci
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  - port: 50000
    targetPort: 50000
    name: slave
  selector:
    k8s-app: jenkins
 # type: LoadBalancer
  type: NodePort
  
  ##完结...
  
